# This file is auto-generated by GoReleaser. Do not edit manually.
# For manual edits, see the .goreleaser.yaml configuration.

class Rl < Formula
  desc "A minimal read-later CLI tool for macOS"
  homepage "https://github.com/bunchhieng/rl"
  url "https://github.com/bunchhieng/rl/releases/download/v1.0.0/rl_1.0.0_darwin_amd64.tar.gz"
  sha256 "REPLACE_WITH_ACTUAL_SHA256"
  version "1.0.0"

  def install
    bin.install "rl"
  end

  test do
    system "#{bin}/rl", "version"
  end
end

